Repository wp-cli/wp-cli, pull requests merged in 2018-10, with the labels that each got.

#4956 Update Composer dependencies (2018-10-01)
  composer.lock
Labels: scope:distribution

#4957 Bump included package-command to v2.0.3
  composer.lock
Labels: scope:distribution

#4961 Update Composer dependencies (2018-10-03)
  composer.lock
Labels: scope:distribution

#4962 Update README to account for the 280-character limit on Twitter
  README.md
Labels: scope:documentation

#4964 Update Composer dependencies (2018-10-05)
  composer.lock
Labels: scope:distribution

#4787 Added `cli cache prune` & `cli cache clear` commands
  features/cli-cache.feature
  php/WP_CLI/FileCache.php
  php/commands/cli.php
  php/commands/src/CLI_Cache_Command.php
  php/commands/src/CLI_Command.php
Labels: command:cli-cache, command:cli-cache-clear, command:cli-cache-prune

#4971 Update Composer dependencies (2018-10-12)
  composer.lock
Labels: scope:framework

#4973 Update Composer dependencies (2018-10-15)
  composer.lock
Labels: scope:distribution

#4975 Update Composer dependencies (2018-10-17)
  composer.lock
Labels: scope:distribution

#4977 Update Composer dependencies (2018-10-19)
  composer.lock
Labels: scope:distribution

#4980 Add Probot `move` support
  .github/move.yml
Labels: scope:distribution

#4986 Update Composer lock file
  composer.lock
Labels: scope:distribution

#4963 Use `dirname()` instead of `..` to locate `wp-config.php` to match Core behavior
  php/utils.php
Labels: internal-api:wp-cli-get-config

#4960 Use "installation" instead of "install" in documentation
  features/utils-wp.feature
  php/class-wp-cli.php
  php/commands/src/CLI_Command.php
Labels: scope:documentation

#4984 Match the way WordPress Core locates `wp-config.php`
  php/utils.php
Labels: internal-api:wp-cli-get-config

#4988 Update Composer dependencies (2018-10-31)
  composer.lock
Labels: scope:distribution

#4985 Improve `--debug` output for `WP_CLI::add_command`
  php/class-wp-cli.php
Labels: internal-api:wp-cli-debug

#4989 Fix parsing of arguments for `WP_CLI::runcommand()` with `launch=false`
  php/utils.php
  tests/test-utils.php
Labels: bug, internal-api:wp-cli-runcommand
