Repository wp-cli/wp-cli, pull requests merged in 2018-02, with the labels that each got.

#4688 Update wp-cli/package-command to v1.0.12
  composer.lock
Labels: scope:distribution

#4613 update `wp cli info`
  features/cli-info.feature
  php/commands/src/CLI_Command.php
Labels: command:cli-info

#4695 Empty domain in framework test after get_sites_by_path change.
  features/framework.feature
Labels: scope:testing

#4622 Script to create the Git pre-commit hook.
  composer.json
  utils/git-setup-pre-commit-hook
Labels: scope:testing

#4697 Remove : from cli update info check.
  php/commands/src/CLI_Command.php
Labels: command:cli-update, scope:testing

#4692 Append uniq id when extracting file from Phar
  php/utils.php
Labels: bug, scope:framework

#4691 Support launching system editor with specific temp file extension
  php/utils.php
Labels: internal-api:wp-cli-utils-launch-editor-for-input, scope:framework

#4696 Only check staged files during the pre-commit PHPCS verification
  utils/git-pre-commit-script
  utils/git-setup-pre-commit-hook
Labels: scope:testing

#4699 Update license copyright date to 2018
  LICENSE
Labels: scope:documentation

#4702 Revert "update `wp cli info`"
  features/cli-info.feature
  php/commands/src/CLI_Command.php
Labels: bug, command:cli-info, command:cli-update
