Repository wp-cli/wp-cli, pull requests merged in 2018-08, with the labels that each got.

#4875 Update Composer dependencies (2018-08-01)
  composer.lock
Labels: scope:distribution

#4877 Update Composer dependencies (2018-08-03)
  composer.lock
Labels: scope:distribution

#4881 Add Inflector class and convenience function for pluralizing nouns
  php/WP_CLI/Inflector.php
  php/utils.php
  tests/test-inflector.php
  tests/test-utils.php
Labels: scope:framework

#4851 Refactoring `wp-cli/wp-cli` to represent the framework only, not the bundle
  .travis.yml
  ci/behat-tags.php
  ci/deploy.sh
  ci/prepare.sh
  ci/sniff.sh
  ci/test.sh
  composer.json
  composer.lock
  features/bootstrap.feature
  features/bootstrap/FeatureContext.php
  features/bootstrap/support.php
  features/cli-bash-completion.feature
  features/cli-info.feature
  features/cli.feature
  features/command.feature
  features/extra/no-mail.php
  features/help.feature
  features/make-phar.feature
  features/runcommand.feature
  features/steps/given.php
  features/steps/then.php
  features/steps/when.php
  php/WP_CLI/AutoloadSplitter.php
  php/WP_CLI/Bootstrap/AutoloaderStep.php
  php/WP_CLI/Bootstrap/IncludeBundledAutoloader.php
  php/WP_CLI/Bootstrap/IncludeFallbackAutoloader.php
  php/WP_CLI/Bootstrap/IncludeFrameworkAutoloader.php
  php/WP_CLI/Bootstrap/RegisterDeferredCommands.php
  php/WP_CLI/Bootstrap/RegisterFrameworkCommands.php
  php/WP_CLI/Runner.php
  php/boot-phar.php
  php/bootstrap.php
  php/class-wp-cli.php
  php/commands/cli.php
  php/commands/help.php
  php/commands/src/Help_Command.php
  php/utils.php
  phpcs.xml.dist
  phpunit.xml.dist
  tests/test-autoload-splitter.php
  tests/test-behat-tags.php
  tests/test-search-replace.php
  utils/make-phar-spec.php
  utils/make-phar.php
  utils/test-phar-download
  utils/update-phar
  utils/wp-cli-rpm.spec
  utils/wp-cli-updatedeb.sh
  utils/wp-cli-updaterpm.sh
Labels: scope:distribution, scope:framework

#4883 Make sure the option command is available
  composer.json
  composer.lock
  features/bootstrap.feature
Labels: scope:distribution, scope:testing

#4886 Debug `debug()` bug
  php/class-wp-cli.php
Labels: bug, internal-api:wp-cli-debug

#4887 Update dependencies
  composer.json
  composer.lock
Labels: scope:distribution

#4888 Add `behat.yml` file for Windows compatibility
  behat.yml
  composer.lock
Labels: scope:distribution

#4897 Bump version to 2.0.0
  VERSION
Labels: scope:distribution

#4898 Bump version to 2.1.0-alpha
  VERSION
Labels: scope:distribution

#4899 Update stable to v2.0.0 and adapt minimum PHP
  README.md
Labels: scope:documentation

#4903 Update Composer dependencies (2018-08-10)
  composer.lock
Labels: scope:distribution

#4914 Update Composer dependencies (2018-08-20)
  composer.lock
Labels: scope:distribution

#4918 Update dependencies and make avoid redefining WP_CLI_ROOT
  composer.json
  composer.lock
  tests/bootstrap.php
Labels: bug, scope:testing

#4906 Automatically rerun failed scenarios
  .travis.yml
  composer.json
Labels: scope:testing

#4916 Make `pick_fields()` work with numeric headers
  php/utils.php
  tests/test-utils.php
Labels: bug, internal-api:wp-cli-utils-format-items, scope:framework

#4920 Adapt `VERSION` to `2.0.1`
  VERSION
Labels: scope:distribution

#4923 Skip releases that lack a downloadable asset
  php/commands/src/CLI_Command.php
Labels: bug, command:cli-check-update, command:cli-update, scope:distribution

#4924 Adapt README.md file for v2.0.1 release
  README.md
  VERSION
Labels: scope:distribution

#4926 Fix `var_export` return in `WP_CLI::print_value`
  php/class-wp-cli.php
Labels: bug, scope:framework

#4927 Update Composer dependencies (2018-08-27)
  composer.lock
Labels: scope:framework

#4930 Update Composer dependencies (2018-08-29)
  composer.lock
Labels: scope:framework

#4928 Check and display help command if requested
  features/help.feature
  features/prompt.feature
  php/WP_CLI/Dispatcher/Subcommand.php
Labels: bug, scope:framework
