Repository wp-cli/wp-cli, pull requests merged in 2018-12, with the labels that each got.

#5014 Bump PHP version to 5.4+ for PHP Compatibility Checker
  phpcs.xml.dist
Labels: scope:testing

#5010 Use custom autoloader to load framework
  features/bootstrap.feature
  php/WP_CLI/Bootstrap/IncludeFrameworkAutoloader.php
Labels: breaking-change, bug, dependent, scope:framework

#5036 Fix override test on Composer stack
  features/bootstrap.feature
  php/bootstrap.php
Labels: scope:framework, scope:testing

#5023 PHPCS: fix up the code base [4] - remove redundant function
  php/WP_CLI/Dispatcher/RootCommand.php
Labels: scope:framework

#5024 PHPCS: fix up the code base [5] - yoda conditions
  php/class-wp-cli.php
  tests/test-utils.php
Labels: scope:framework

#5025 PHPCS: fix up the code base [8] - assignments in conditions
  php/commands/src/CLI_Command.php
  php/commands/src/Help_Command.php
  utils/contrib-list.php
Labels: scope:framework

#5026 PHPCS: fix up the code base [9] - function calls in for condition
  php/commands/src/Help_Command.php
Labels: scope:framework

#5028 PHPCS: fix up the code base [11] - use self
  php/class-wp-cli.php
Labels: scope:framework

#5030 PHPCS: fix up the code base [13] - assignments in conditions
  php/WP_CLI/Bootstrap/IncludeFallbackAutoloader.php
  php/WP_CLI/Configurator.php
  php/WP_CLI/Dispatcher/CommandFactory.php
  php/WP_CLI/Dispatcher/Subcommand.php
  php/WP_CLI/Extractor.php
  php/WP_CLI/Runner.php
  php/utils-wp.php
  php/utils.php
  php/wp-settings-cli.php
Labels: scope:framework

#5031 PHPCS: fix up the code base [14] - assignments in conditions
  php/class-wp-cli.php
Labels: scope:framework

#5032 PHPCS: fix up the code base [17] - require vs include
  php/boot-fs.php
Labels: scope:framework

#5038 Remove `ext-posix` requirement from Composer file
  composer.json
  composer.lock
Labels: scope:distribution

#5039 Bump PHP version check in bootstrap code to v5.4+
  php/boot-fs.php
Labels: breaking-change, scope:distribution

#5029 PHPCS: fix up the code base [12] - assignment within function call
  php/WP_CLI/Bootstrap/IncludePackageAutoloader.php
  php/WP_CLI/Bootstrap/LoadRequiredCommand.php
Labels: scope:framework

#5040 PHPCS: fix up the code base [1] - whitespace
  php/WP_CLI/Completions.php
  php/WP_CLI/Configurator.php
  php/WP_CLI/Dispatcher/CommandFactory.php
  php/WP_CLI/Dispatcher/CompositeCommand.php
  php/WP_CLI/Dispatcher/RootCommand.php
  php/WP_CLI/Dispatcher/Subcommand.php
  php/WP_CLI/DocParser.php
  php/WP_CLI/Inflector.php
  php/WP_CLI/Process.php
  php/WP_CLI/Runner.php
  php/WP_CLI/WpHttpCacheManager.php
  php/class-wp-cli.php
  php/utils-wp.php
  php/utils.php
  tests/bootstrap.php
  tests/test-arg-validation.php
  tests/test-commandfactory.php
  tests/test-configurator.php
  tests/test-doc-parser.php
  tests/test-extractor.php
  tests/test-file-cache.php
  tests/test-help.php
  tests/test-logging.php
  tests/test-process.php
  tests/test-synopsis.php
  tests/test-utils.php
  utils/contrib-list.php
  utils/get-package-require-from-composer.php
Labels: scope:framework

#5041 PHPCS: fix up the code base [16] - operator precedence
  php/WP_CLI/Dispatcher/CommandFactory.php
  php/WP_CLI/FileCache.php
  php/WP_CLI/Runner.php
Labels: scope:framework

#5027 PHPCS: fix up the code base [10] - logic obfuscation
  php/WP_CLI/Dispatcher/CommandNamespace.php
  php/WP_CLI/Dispatcher/CompositeCommand.php
Labels: scope:framework

#5043 PHPCS: fix up the code base [7] - closure declaration
  tests/test-utils.php
Labels: scope:framework

#5044 PHPCS: fix up the code base [15] - assignments in conditions
  php/WP_CLI/Dispatcher/CommandFactory.php
Labels: scope:framework

#5015 Skip associative arguments that were already provided on `--prompt`
  features/prompt.feature
  php/WP_CLI/Dispatcher/Subcommand.php
Labels: parameter:prompt

#5045 PHPCS: fix up the code base [6] - multi-line function calls
  tests/test-doc-parser.php
  tests/test-extractor.php
  tests/test-logging.php
  tests/test-utils.php
Labels: scope:testing

#5049 Properly reorder synopsis passed in via `$args`
  features/command.feature
  php/WP_CLI/SynopsisParser.php
Labels: bug, internal-api:wp-cli-add-command

#5051 Update Composer dependencies (2018-12-17)
  composer.lock
Labels: scope:distribution

#5055 Fix typo: Autolaoder => Autoloader
  php/WP_CLI/Bootstrap/IncludeFrameworkAutoloader.php
Labels: bug, scope:bootstrap
