Repository wp-cli/wp-cli, pull requests merged in 2018-04, with the labels that each got.

#4758 Show help text even when `proc_(open|close)` aren't available
  features/help.feature
  php/commands/help.php
  php/config-spec.php
Labels: bug, scope:framework

#4755 Only run `phpcs` against PHP files on pre-commit hook
  utils/git-pre-commit-script
Labels: bug, scope:testing

#4759 Improve the descriptions of the `--skip-plugins` and `--skip-themes` flags
  php/config-spec.php
Labels: scope:documentation, scope:framework

#4761 Update Composer dependencies (2018-04-04)
  composer.lock
Labels: scope:distribution

#4764 Update Composer dependencies (2018-04-09)
  composer.lock
Labels: scope:framework

#4765 Add a missing accepted output format to `wp cli alias`
  php/commands/src/CLI_Command.php
Labels: command:cli-alias

#4770 Update Composer dependencies (2018-04-13)
  composer.lock
Labels: scope:distribution

#4778 Bugfix release 1.5.1
  README.md
  composer.lock
  features/cli-info.feature
  features/cli.feature
  features/make-phar.feature
  features/runcommand.feature
Labels: scope:distribution
