Repository wp-cli/wp-cli, pull requests merged in 2018-05, with the labels that each got.

#4772 Update Composer dependencies (2018-04-16)
  composer.lock
Labels: scope:distribution

#4785 Update Composer dependencies (2018-05-02)
  composer.lock
Labels: scope:distribution

#4802 Update Composer dependencies (2018-05-28)
  composer.lock
Labels: scope:distribution

#4803 Switch to fixed package command
  composer.lock
Labels: bug, command:package-install, scope:distribution

#4804 Update packages to fix broken tests due to WP5.0
  composer.lock
Labels: scope:testing

#4807 Use latest search-replace package to fix tests broken due to privacy policy change
  composer.lock
Labels: bug, scope:testing

#4806 Turn latest into version number
  ci/test.sh
Labels: bug, scope:testing
