Repository wp-cli/wp-cli, pull requests merged in 2018-03, with the labels that each got.

#4707 Require minimum PHP 5.4
  .travis.yml
  composer.json
  composer.lock
  php/boot-fs.php
Labels: scope:framework

#4715 Revert "Require minimum PHP 5.4"
  .travis.yml
  composer.json
  composer.lock
  features/bootstrap.feature
  php/boot-fs.php
Labels: scope:framework

#4716 Undo temp one-off require-php-5.4 in bootstrap test.
  features/bootstrap.feature
Labels: scope:testing

#4712 Update Composer dependencies (2018-02-28)
  composer.lock
  php/WP_CLI/Formatter.php
  php/WP_CLI/Runner.php
  php/utils.php
Labels: scope:framework

#4711 Skip pre-commit hook in auto-composer-update
  utils/auto-composer-update.sh
Labels: scope:framework

#4719 Update Composer dependencies (2018-03-05)
  composer.lock
Labels: scope:framework

#4730 Update Composer dependencies (2018-03-14)
  composer.lock
Labels: scope:framework

#4731 Update Composer dependencies (2018-03-16)
  composer.lock
Labels: scope:framework

#4718 Introducing `\WP_CLI\Utils\normalize_path` function. Using it for ABSPATH constant.
  php/WP_CLI/Runner.php
  php/utils.php
  tests/test-utils.php
Labels: scope:framework

#4736 Skip wp_blogmeta table for back compat
  features/utils-wp.feature
Labels: scope:testing

#4734 Update Composer dependencies (2018-03-20)
  composer.lock
Labels: scope:framework

#4737 Update Composer dependencies (2018-03-21)
  composer.lock
Labels: scope:framework

#4742 Update Composer dependencies (2018-03-23)
  composer.lock
Labels: scope:distribution

#4754 Update Composer dependencies (2018-03-30)
  composer.lock
Labels: scope:distribution

#4756 Include sublinks in README to popular installation methods
  README.md
Labels: scope:documentation

#4743 Abspath defined
  features/runner.feature
  php/WP_CLI/Runner.php
Labels: scope:bootstrap, scope:framework
