Repository wp-cli/wp-cli, pull requests merged in 2018-07, with the labels that each got.

#4839 Locking wp-completion.bash to v1.5.1
  README.md
Labels: scope:documentation

#4841 Fixing issues in bin/wp
  bin/wp
Labels: scope:bootstrap

#4840 Additional quoting in ci/prepare.sh
  ci/prepare.sh
Labels: scope:distribution

#4842 Fixing issues in ci/deploy.sh
  ci/deploy.sh
  features/skip-themes.feature
Labels: bug, scope:testing

#4843 Fixing skip-theme tests
  features/skip-themes.feature
Labels: scope:testing

#4845 Remove WP 4.4 requirement
  features/skip-themes.feature
Labels: scope:testing

#4853 Fall back to full string instead of $mode on PHP < 7
  php/commands/src/CLI_Command.php
  phpcs.xml.dist
Labels: bug, command:cli-info

#4850 Update Composer dependencies (2018-07-18)
  composer.lock
Labels: scope:distribution

#4861 Trigger new 'cli_init' hook during WordPress plugins_loaded action.
  features/command.feature
  php/WP_CLI/Runner.php
Labels: scope:framework

#4854 add template for core-command to phar
  composer.json
  composer.lock
  templates/plugin-status.mustache
  templates/theme-status.mustache
  templates/versions.mustache
  utils/make-phar.php
Labels: scope:distribution

#4863 Update Composer dependencies (2018-07-23)
  composer.lock
Labels: scope:distribution

#4866 Update Composer dependencies (2018-07-25)
  composer.lock
Labels: scope:distribution

#4873 Adapt regular expression to skip wiki links
  features/make-phar.feature
Labels: scope:testing

#4864 Fix PHP version check
  php/commands/src/CLI_Command.php
Labels: scope:framework

#4870 Update Composer dependencies (2018-07-30)
  composer.lock
Labels: scope:distribution

#4867 PHPCS Config Refresh
  composer.json
  composer.lock
  php/WP_CLI/Bootstrap/LoadRequiredCommand.php
  php/WP_CLI/Completions.php
  php/WP_CLI/Configurator.php
  php/WP_CLI/Dispatcher/CommandAddition.php
  php/WP_CLI/Dispatcher/CommandFactory.php
  php/WP_CLI/Dispatcher/CommandNamespace.php
  php/WP_CLI/Dispatcher/CompositeCommand.php
  php/WP_CLI/Dispatcher/Subcommand.php
  php/WP_CLI/DocParser.php
  php/WP_CLI/Extractor.php
  php/WP_CLI/FileCache.php
  php/WP_CLI/Formatter.php
  php/WP_CLI/Iterators/Query.php
  php/WP_CLI/Iterators/Table.php
  php/WP_CLI/Loggers/Base.php
  php/WP_CLI/Loggers/Regular.php
  php/WP_CLI/PackageManagerEventSubscriber.php
  php/WP_CLI/Process.php
  php/WP_CLI/Runner.php
  php/WP_CLI/SynopsisParser.php
  php/WP_CLI/SynopsisValidator.php
  php/WP_CLI/WpHttpCacheManager.php
  php/bootstrap.php
  php/class-wp-cli.php
  php/commands/help.php
  php/commands/src/CLI_Command.php
  php/config-spec.php
  php/utils-wp.php
  php/utils.php
  php/wp-cli.php
  php/wp-settings-cli.php
  phpcs.xml.dist
Labels: scope:framework
