Repository wp-cli/wp-cli, pull requests merged in 2019-08, with the labels that each got.

#5261 Make extraction more robust
  php/WP_CLI/Extractor.php
  tests/test-extractor.php
Labels: scope:framework

#5262 Update Composer dependencies (2019-08-13)
  composer.lock
Labels: scope:distribution

#5242 Improve "Adding deferred command..." debug output (Closes: #4893)
  php/WP_CLI/Bootstrap/RegisterDeferredCommands.php
Labels: internal-api:wp-cli-debug

#5241 Fix `parse_url` scheme bug
  php/utils.php
  tests/test-utils.php
Labels: scope:framework

#5263 Adapt branch alias for v2.4.0
  composer.json
  composer.lock
Labels: scope:distribution

#5266 Update the README for the current version
  README.md
Labels: scope:documentation

#5270 Fix PHPDoc annotation for Formatter:display_items
  php/WP_CLI/Formatter.php
Labels: scope:documentation

#5271 Replace is_a() with instanceof operator
  php/WP_CLI/Formatter.php
  php/class-wp-cli.php
  php/utils-wp.php
Labels: scope:framework

#5273 PHP 7.4 Compatibility: Update `implode()` calls.
  php/WP_CLI/DocParser.php
  php/commands/src/Help_Command.php
Labels: scope:framework
