Repository wp-cli/wp-cli, pull requests merged in 2019-11, with the labels that each got.

#5303 Load template functions in Runner
  php/WP_CLI/Runner.php
Labels: scope:framework

#5306 Patch `mustache/mustache` to avoid throwing notices on PHP 7.4
  .travis.yml
  composer.json
  composer.lock
  php/WP_CLI/Dispatcher/CommandFactory.php
Labels: upstream-bug

#5307 Sync Travis
  .travis.yml
Labels: scope:distribution

#5297 Converted alias, cli, cache, and help commands help summaries to use third-person singular verbs.
  php/commands/src/CLI_Alias_Command.php
  php/commands/src/CLI_Cache_Command.php
  php/commands/src/CLI_Command.php
  php/commands/src/Help_Command.php
Labels: scope:documentation

#5289 Use warning instead of colorize to fix warning output
  php/WP_CLI/Runner.php
Labels: bug, scope:framework

#5309 Adapt regex in `parse_str_to_argv()`
  php/utils.php
  tests/test-utils.php
Labels: bug, scope:framework

#5308 Fix access to undefined host index
  php/WP_CLI/FileCache.php
Labels: bug, internal-api:wp-cli-file-cache

#5310 Polyfill `is_customize_preview()`
  php/WP_CLI/Runner.php
Labels: bug, scope:framework

#5311 Update feature request template from central version
  .github/ISSUE_TEMPLATE/2-FEATURE_REQUEST.md
Labels: scope:documentation

#5313 Bump VERSION and adapt README for release 2.4.0
  README.md
  VERSION
Labels: scope:documentation

#5314 Change timing of when to polyfill `is_customize_preview()`
  php/WP_CLI/Runner.php
Labels: bug, scope:framework

#5316 Update link to Homebrew
  .github/ISSUE_TEMPLATE/4-REGULAR_RELEASE_CHECKLIST.md
  .github/ISSUE_TEMPLATE/5-PATCH_RELEASE_CHECKLIST.md
Labels: scope:documentation

#5317 Add notes about rpm and deb builds
  .github/ISSUE_TEMPLATE/4-REGULAR_RELEASE_CHECKLIST.md
  .github/ISSUE_TEMPLATE/5-PATCH_RELEASE_CHECKLIST.md
Labels: scope:documentation

#5318 Update brew formula refresh instructions
  .github/ISSUE_TEMPLATE/4-REGULAR_RELEASE_CHECKLIST.md
  .github/ISSUE_TEMPLATE/5-PATCH_RELEASE_CHECKLIST.md
Labels: scope:documentation

#5319 Adapt branch alias for v2.5.0
  composer.json
  composer.lock
  php/wp-settings-cli.php
Labels: scope:distribution
