Repository wp-cli/wp-cli, pull requests merged in 2019-03, with the labels that each got.

#5094 Fix failing test under WP 5.1
  features/help.feature
Labels: scope:testing

#5090 Update regex to be more accurate
  php/utils.php
  tests/test-utils.php
Labels: bug, scope:framework

#5099 update docblock for add_command() to properly reflect the return value
  php/class-wp-cli.php
Labels: internal-api:wp-cli-add-command, scope:documentation

#5103 Fix FileCache::export() not ensuring parent directories exist for $target
  php/WP_CLI/FileCache.php
  tests/test-file-cache.php
Labels: bug, command:cache

#5102 Switch `ext-readline` to 'suggest' instead of a hard requirement
  composer.json
  composer.lock
Labels: scope:distribution

#5112 Fixed documented return type for `make_progress_bar()`
  php/utils.php
Labels: bug, internal-api:wp-cli-utils-make-progress-bar, scope:documentation

#5113 Corrected Type Docs & Usage
  php/WP_CLI/Dispatcher/CommandFactory.php
  php/WP_CLI/Dispatcher/CompositeCommand.php
  php/WP_CLI/Extractor.php
  php/WP_CLI/Formatter.php
  php/WP_CLI/Iterators/Query.php
  php/WP_CLI/Loggers/Base.php
  php/class-wp-cli.php
  php/dispatcher.php
  php/utils.php
Labels: bug, scope:documentation

#5115 Bug fix for Issue #5109
  php/utils.php
  tests/test-utils.php
Labels: bug, scope:framework
