Repository wp-cli/wp-cli, pull requests merged in 2019-04, with the labels that each got.

#5126 Internalize `array_column()` shim, because package is abandoned
  composer.json
  composer.lock
  php/WP_CLI/Bootstrap/IncludeFrameworkAutoloader.php
  php/compat.php
  php/wp-cli.php
Labels: scope:framework

#5130 Move PHP 5.4 tests from `WP_VERSION` `latest` to `5.1`
  .travis.yml
Labels: scope:distribution

#5119 Introduce ability to override wp-config.php path with env var WP_CONFIG_PATH
  features/wp-config.feature
  php/utils.php
Labels: scope:framework

#5142 Fix: Limit ranges of PHP versions
  composer.json
  composer.lock
Labels: scope:distribution

#5144 CS: clean up after merges
  php/WP_CLI/Dispatcher/Subcommand.php
  php/WP_CLI/Runner.php
  tests/test-utils.php
Labels: scope:framework

#5145 PHPCS: fix up the code base [18] - one property per statement
  php/WP_CLI/Dispatcher/CompositeCommand.php
  php/WP_CLI/Runner.php
  php/class-wp-cli.php
Labels: scope:framework

#5146 PHPCS: fix up the code base [19] - strict comparisons
  php/class-wp-cli.php
  php/utils.php
Labels: scope:framework

#5147 PHPCS: fix up the code base [20] - strict array comparisons
  php/WP_CLI/Dispatcher/Subcommand.php
Labels: scope:framework

#5148 PHPCS: fix up the code base [21] - use `self`
  php/class-wp-cli.php
Labels: scope:framework

#5149 PHPCS: fix up the code base [22] - no \ prefixed use statements
  php/WP_CLI/ComposerIO.php
  php/WP_CLI/Dispatcher/CompositeCommand.php
  php/WP_CLI/Dispatcher/RootCommand.php
  php/WP_CLI/PackageManagerEventSubscriber.php
  php/class-wp-cli.php
  php/commands/src/CLI_Command.php
  php/utils.php
  php/wp-settings-cli.php
Labels: scope:framework

#5150 PHPCS: fix up the code base [23] - touch up inline comment
  php/WP_CLI/FileCache.php
  php/class-wp-cli.php
Labels: scope:documentation

#5152 PHPCS: fix up the code base [25] - rename a local variable
  php/utils.php
Labels: scope:framework

#5153 PHPCS: fix up the code base [26] - rename a local variable
  php/WP_CLI/DocParser.php
Labels: scope:framework

#5155 PHPCS: fix up the code base [28] - rename a local variable
  php/WP_CLI/FileCache.php
Labels: scope:framework

#5156 PHPCS: fix up the code base [29] - rename two local variables
  tests/test-logging.php
Labels: scope:testing

#5157 PHPCS: fix up the code base [30] - rename a private property
  php/WP_CLI/Runner.php
Labels: scope:framework

#5158 PHPCS: fix up the code base [34] - rename a private property
  php/WP_CLI/Inflector.php
Labels: scope:framework

#5159 PHPCS: fix up the code base [35] - rename a private property
  php/WP_CLI/Iterators/CSV.php
Labels: scope:framework

#5151 PHPCS: fix up the code base [24] - touch up inline comments
  php/WP_CLI/Configurator.php
Labels: scope:documentation

#5163 PHPCS: fix up the code base [32] - rename a private property
  php/WP_CLI/Runner.php
Labels: scope:framework

#5164 PHPCS: fix up the code base [37] - rename a private property
  php/WP_CLI/Iterators/CSV.php
Labels: scope:framework

#5165 PHPCS: fix up the code base [33] - rename a private property
  php/WP_CLI/Runner.php
Labels: scope:framework

#5141 Add checklists for regular and patch releases
  .github/ISSUE_TEMPLATE
  .github/ISSUE_TEMPLATE/1-BUG_REPORT.md
  .github/ISSUE_TEMPLATE/2-FEATURE_REQUEST.md
  .github/ISSUE_TEMPLATE/3-SUPPORT_REQUEST.md
  .github/ISSUE_TEMPLATE/4-REGULAR_RELEASE_CHECKLIST.md
  .github/ISSUE_TEMPLATE/5-PATCH_RELEASE_CHECKLIST.md
Labels: scope:documentation

#5168 Add default titles to release checklists
  .github/ISSUE_TEMPLATE/4-REGULAR_RELEASE_CHECKLIST.md
  .github/ISSUE_TEMPLATE/5-PATCH_RELEASE_CHECKLIST.md
Labels: scope:distribution

#5170 Justify the use of `mt_rand()`
  php/class-wp-cli.php
  php/utils.php
Labels: scope:framework

#5172 Whitelist already escaped SQL for PHPCS
  php/utils-wp.php
Labels: scope:framework

#5177 Whitelist `_line` method as it is being used in third-party code
  php/WP_CLI/Loggers/Base.php
Labels: scope:framework

#5176 Use strict comparisons
  php/WP_CLI/Formatter.php
  php/WP_CLI/SynopsisValidator.php
Labels: scope:framework

#5174 Rename camelCase properties to snake_case
  php/WP_CLI/DocParser.php
  php/WP_CLI/FileCache.php
Labels: breaking-change, scope:framework

#5173 Rename camelCase methods into snake_case
  php/WP_CLI/Bootstrap/BootstrapState.php
  php/WP_CLI/Bootstrap/DefineProtectedCommands.php
  php/WP_CLI/Bootstrap/IncludePackageAutoloader.php
  php/WP_CLI/Bootstrap/LoadRequiredCommand.php
Labels: scope:framework

#5175 Remove access to inexistent `$STDERR` property
  php/WP_CLI/Process.php
Labels: scope:framework

#5171 Replace or justify the usage of the `strip_tags()` function
  php/WP_CLI/ComposerIO.php
  php/WP_CLI/UpgraderSkin.php
  php/utils-wp.php
Labels: scope:framework

#5181 Remove code comment
  php/utils-wp.php
Labels: scope:framework

#5187 Revert "Rename camelCase methods into snake_case"
  php/WP_CLI/Bootstrap/BootstrapState.php
  php/WP_CLI/Bootstrap/DefineProtectedCommands.php
  php/WP_CLI/Bootstrap/IncludePackageAutoloader.php
  php/WP_CLI/Bootstrap/LoadRequiredCommand.php
Labels: bug

#5184 Whitelist "useless" override
  php/WP_CLI/Loggers/Execution.php
Labels: scope:framework

#5188 Revert "PHPCS: fix up the code base [20] - strict array comparisons"
  php/WP_CLI/Dispatcher/Subcommand.php
Labels: bug

#5178 Fix typos and improve readability of inline docs
  php/class-wp-cli.php
  php/utils-wp.php
  php/utils.php
  php/wp-cli.php
  php/wp-settings-cli.php
Labels: scope:documentation

#5183 Whitelist urlencode
  php/utils.php
Labels: scope:framework

#5182 Replace or justify the usage of the `parse_url()` function
  php/WP_CLI/FileCache.php
  php/WP_CLI/Runner.php
  php/WP_CLI/WpHttpCacheManager.php
  php/utils.php
Labels: scope:framework

#5122 Add command to manage aliases
  features/aliases.feature
  php/commands/cli.php
  php/commands/src/CLI_Alias_Command.php
  php/commands/src/CLI_Command.php
Labels: command:cli-alias

#5193 Avoid double registration of commands
  php/class-wp-cli.php
Labels: bug, internal-api:wp-cli-add-command, scope:framework

#5128 Add flags to include / exclude views in wp_get_table_names()
  features/utils-wp.feature
  php/utils-wp.php
Labels: command:db-tables

#5195 Update sponsors list
  README.md
Labels: scope:documentation

#5199 Fix last remaining usage of `strip_tags`
  php/utils-wp.php
Labels: scope:framework

#5194 Add `aliases` subcommand for backwards compatibility
  features/aliases.feature
  php/WP_CLI/Runner.php
Labels: command:cli-alias

#5198 Implement CS checking based on the `WP_CLI_CS` ruleset
  .gitignore
  composer.json
  composer.lock
  php/WP_CLI/Bootstrap/BootstrapState.php
  php/WP_CLI/Dispatcher/Subcommand.php
  php/WP_CLI/FileCache.php
  php/WP_CLI/Formatter.php
  php/WP_CLI/Runner.php
  php/WP_CLI/UpgraderSkin.php
  php/class-wp-cli.php
  php/commands/src/Help_Command.php
  php/compat.php
  php/utils-wp.php
  php/utils.php
  php/wp-settings-cli.php
  phpcs.xml.dist
  tests/phpunit6-compat.php
  tests/test-bundled-commands.php
  tests/test-logging.php
Labels: dependent, scope:framework

#5203 Always reattach subcommands
  php/class-wp-cli.php
Labels: bug, internal-api:wp-cli-add-command

#5197 Add warning message to let the user know when `WP_CLI_SSH_PRE_CMD` is in use
  php/WP_CLI/Runner.php
Labels: scope:framework

#5206 Update dependencies 2019-04-25
  composer.lock
Labels: scope:distribution

#5207 Update dependencies 2019-04-25-2
  composer.lock
Labels: scope:distribution

#5208 Bump version to 2.2.0
  README.md
  VERSION
Labels: scope:distribution
