Repository wp-cli/wp-cli, pull requests merged in 2019-02, with the labels that each got.

#5066 Add `dependencies.yml` file to define auto-updates
  dependencies.yml
Labels: scope:distribution

#5073 Update the Travis build to include PHP 7.3.
  .travis.yml
Labels: scope:testing

#5078 Update ISSUE_TEMPLATE
  .github/ISSUE_TEMPLATE
Labels: scope:documentation

#5068 Ensure cache directories are accessibles
  features/cli-cache.feature
  php/WP_CLI/FileCache.php
Labels: command:cli-cache

#5080 fix incorrect link in readme
  README.md
Labels: scope:documentation
