Repository wp-cli/wp-cli, pull requests merged in 2019-09, with the labels that each got.

#5283 Add PHP-version-specific traits to extend the upgrader skin feedback method
  php/WP_CLI/Compat/FeedbackMethodTrait.php
  php/WP_CLI/Compat/Min_PHP_5_4/FeedbackMethodTrait.php
  php/WP_CLI/Compat/Min_PHP_5_6/FeedbackMethodTrait.php
  php/WP_CLI/UpgraderSkin.php
Labels: breaking-change

#5281 Example for adding alias is missing '@'
  php/commands/src/CLI_Alias_Command.php
Labels: command:cli-alias, scope:documentation

#5280 Fix return type of `make_progress_bar()`
  php/utils.php
Labels: bug, scope:documentation
