Repository wp-cli/wp-cli, pull requests merged in 2020-04, with the labels that each got.

#5370 Allow for array of strings in ComposerIO
  php/WP_CLI/ComposerIO.php
Labels: command:package, scope:distribution

#5336 fix typos and docs standards
  php/WP_CLI/Bootstrap/RegisterDeferredCommands.php
  php/WP_CLI/Completions.php
  php/WP_CLI/Configurator.php
  php/WP_CLI/Extractor.php
  php/WP_CLI/FileCache.php
  php/WP_CLI/Loggers/Quiet.php
  php/WP_CLI/Loggers/Regular.php
  php/commands/src/CLI_Command.php
  php/commands/src/Help_Command.php
Labels: scope:documentation

#5375 Remove is-bundled-command method with test-case
  php/utils.php
  tests/test-bundled-commands.php
Labels: breaking-change, scope:distribution

#5371 Fix Travis CI `sudo` warning
  .travis.yml
Labels: scope:distribution

#5366 Add $wp_config_path param for get_wp_config_code
  php/WP_CLI/Runner.php
Labels: internal-api:wp-cli-get-config

#5384 Let `Utils\run_mysql_command()` return data
  features/utils.feature
  php/utils.php
Labels: breaking-change, scope:framework

#5386 Add database info to `cli info` command
  php/commands/src/CLI_Command.php
  php/utils.php
Labels: command:cli-info

#5381 Bump Travis CI OS from `trusty` to `xenial`
  .travis.yml
  composer.lock
  features/bootstrap.feature
Labels: scope:testing

#5380 Enforce PHP 7.4 compatibility in Travis CI
  .travis.yml
  composer.lock
Labels: scope:testing
