Repository wp-cli/wp-cli, pull requests merged in 2020-09, with the labels that each got.

#5443 Fix a broken link in the README file
  README.md
Labels: scope:documentation

#5423 Allow user to suppress global parameters info from help display
  features/help.feature
  php/WP_CLI/Dispatcher/CompositeCommand.php
  templates/man-params.mustache
Labels: scope:documentation, scope:framework

#5421 Updated license date
  LICENSE
Labels: scope:documentation

#5436 Add support for Redis Object Cache
  php/utils-wp.php
Labels: command:cache-type, scope:framework

#5420 Add $interactive arg for run_mysql_command()
  php/utils.php
Labels: scope:framework

#5445 Update dependencies 2020-09-29
  composer.lock
  php/WP_CLI/Dispatcher/Subcommand.php
Labels: scope:distribution
