Repository wp-cli/wp-cli, pull requests merged in 2020-07, with the labels that each got.

#5417 Fix `SERVER_PORT` JSON encoding failure
  features/flags.feature
Labels: scope:testing

#5419 Add support for comma-separated flag values
  features/command.feature
  php/WP_CLI/Dispatcher/Subcommand.php
Labels: scope:framework

#5411 Create a default global config file if it does not exist
  composer.json
  composer.lock
  php/WP_CLI/Runner.php
  php/commands/src/CLI_Alias_Command.php
Labels: command:cli-alias
