Repository wp-cli/wp-cli, pull requests merged in 2020-06, with the labels that each got.

#5405 Throw exception when misusing `error_to_string()`
  php/class-wp-cli.php
  tests/test-wp-cli.php
Labels: bug

#5406 Bump PHPCS compatibility tests to new PHP 5.6+ minimum
  phpcs.xml.dist
Labels: scope:testing

#5408 Updated minimum required PHP version too 5.6
  composer.json
  php/WP_CLI/Loggers/Execution.php
  php/boot-fs.php
  php/utils.php
Labels: scope:distribution

#5407 Include classmap in order to fix composer 2.0 deprecation notices.
  composer.json
Labels: scope:bootstrap
