Repository wp-cli/wp-cli, pull requests merged in 2020-10, with the labels that each got.

#5450 Missing @return tag in function/method PHPDoc comment
  php/WP_CLI/WpHttpCacheManager.php
Labels: scope:documentation

#5455 Only suppress global parameters if set as true
  features/help.feature
  php/WP_CLI/Dispatcher/CompositeCommand.php
Labels: scope:framework

#5454 Add global parameter for executing php
  features/bootstrap.feature
  features/cli.feature
  php/WP_CLI/Bootstrap/LoadExecCommand.php
  php/bootstrap.php
  php/config-spec.php
Labels: scope:framework

#5448 Allow root from environment
  php/WP_CLI/Runner.php
Labels: scope:framework

#5457 Fix non static methods in Extractor_Test class call statically
  tests/test-extractor.php
Labels: bug, scope:testing

#5461 Update Composer dependencies - 2020-10-31
  composer.lock
Labels: scope:distribution
