Repository wp-cli/wp-cli, pull requests merged in 2021-07, with the labels that each got.

#5511 Allow WP_DEBUG_LOG to override the debug.log location.
  php/utils-wp.php
Labels: bug, internal-api:wp-cli-debug

#5545 Update Composer lock file
  composer.lock
Labels: scope:distribution

#5546 Fix OOM issues when exporting to STDOUT
  composer.lock
  features/utils.feature
  php/utils.php
Labels: bug, scope:framework

#5549 Make logger accessible and add colorization control to `Quiet` logger
  php/WP_CLI/Loggers/Quiet.php
  php/WP_CLI/Runner.php
  php/class-wp-cli.php
  tests/test-extractor.php
  tests/test-file-cache.php
  tests/test-utils.php
Labels: internal-api:wp-cli-colorize, scope:framework

#5550 Update Composer lock file - 2021-07-26
  composer.lock
  features/flags.feature
Labels: scope:distribution

#5552 Change "Fake Site" site name to "WordPress" wp core multisite-install subcommand
  php/WP_CLI/Runner.php
Labels: command:core-multisite-install
