Repository wp-cli/wp-cli, pull requests merged in 2021-12, with the labels that each got.

#5582 Fix default `mysqli` error reporting mode for PHP 8.1+
  php/WP_CLI/Runner.php
Labels: scope:framework, bug

#5584 Re-add subcommands on all composite commands that are overwritten
  .gitignore
  composer.json
  composer.lock
  features/aliases.feature
  features/command.feature
  features/config.feature
  features/flags.feature
  features/framework.feature
  features/help.feature
  features/runcommand.feature
  php/WP_CLI/Dispatcher/CompositeCommand.php
  php/WP_CLI/Runner.php
  php/class-wp-cli.php
  tests/WP_CLI/WpOrgApiTest.php
  tests/bootstrap.php
  tests/phpunit6-compat.php
  tests/test-arg-validation.php
  tests/test-commandfactory.php
  tests/test-configurator.php
  tests/test-doc-parser.php
  tests/test-extractor.php
  tests/test-file-cache.php
  tests/test-help.php
  tests/test-inflector.php
  tests/test-logging.php
  tests/test-process.php
  tests/test-synopsis.php
  tests/test-utils.php
  tests/test-wp-cli.php
  tests/test-wp-version-compare.php
Labels: scope:framework, bug

#5588 Use Mustache work-around for PHP 8.1 compat
  composer.json
  php/WP_CLI/Compat/MustacheTokenizer.php
  php/utils.php
Labels: scope:framework, upstream-bug

#5590 Revert addition of the Mustache PHP 8.1 workaround and update dependency
  composer.json
  php/WP_CLI/Compat/MustacheTokenizer.php
  php/utils.php
Labels: scope:distribution

#5591 Check `github.repository_owner` in automerge workflow
  .github/workflows/automerge.yml
Labels: scope:distribution
