Repository wp-cli/wp-cli, pull requests merged in 2021-05, with the labels that each got.

#5516 Update docblocks for methods that accept error objects
  php/class-wp-cli.php
Labels: scope:documentation

#5520 Harden error message on failed cache directory creation
  php/WP_CLI/FileCache.php
Labels: bug, internal-api:wp-cli-file-cache

#5514 Use custom certificate if provided
  php/utils.php
  tests/test-utils.php
Labels: internal-api:wp-cli-utils-http-request

#5507 Fix 5463 `Utils\http_request` verify option
  php/utils.php
  tests/mock-requests-transport.php
  tests/test-utils.php
Labels: bug, internal-api:wp-cli-utils-http-request

#5522 Add missing `$pipes` variables when creating processes
  php/WP_CLI/Process.php
  php/utils.php
Labels: bug, scope:framework

#5524 Update Composer dependencies - 2021-05-08
  composer.lock
Labels: scope:distribution

#5399 Add `regenerate-readme` GitHub Action workflow
  .github/workflows/automerge.yml
  .github/workflows/regenerate-readme.yml
Labels: scope:documentation

#5523 Disable automatic retry by default on certificate validation error
  php/class-wp-cli.php
  php/commands/src/CLI_Command.php
  php/utils-wp.php
  php/utils.php
  tests/test-utils.php
Labels: breaking-change, internal-api:wp-cli-utils-http-request

#5527 Move fetcher implementations back into framework
  php/WP_CLI/Fetchers/Base.php
  php/WP_CLI/Fetchers/Comment.php
  php/WP_CLI/Fetchers/Post.php
  php/WP_CLI/Fetchers/Site.php
  php/WP_CLI/Fetchers/User.php
  php/WP_CLI/Runner.php
Labels: bug, scope:framework

#5529 Require v1.8 of `Requests`
  composer.json
  composer.lock
Labels: scope:distribution

#5533 Update min PHP version to 5.6
  README.md
Labels: scope:documentation
