Repository wp-cli/wp-cli, pull requests merged in 2021-11, with the labels that each got.

#5575 Updated default branch for roave/security-advisories
  composer.json
Labels: scope:distribution

#5576 Cache: Changeable cache size.
  php/class-wp-cli.php
Labels: internal-api:wp-cli-file-cache

#5563 Fix regression that broke extending existing commands
  features/bootstrap.feature
  php/class-wp-cli.php
Labels: scope:framework

#5564 Fixed wrong variable used in parsing args.
  php/WP_CLI/Configurator.php
Labels: scope:framework, bug

#5581 Add `--context` flag
  features/cli.feature
  features/config.feature
  features/context.feature
  features/flags.feature
  features/hook.feature
  php/WP_CLI/Bootstrap/InitializeContexts.php
  php/WP_CLI/Bootstrap/LaunchRunner.php
  php/WP_CLI/Context.php
  php/WP_CLI/Context/Admin.php
  php/WP_CLI/Context/Auto.php
  php/WP_CLI/Context/Cli.php
  php/WP_CLI/Context/Frontend.php
  php/WP_CLI/ContextManager.php
  php/WP_CLI/Runner.php
  php/bootstrap.php
  php/class-wp-cli.php
  php/config-spec.php
Labels: scope:framework
