Repository wp-cli/wp-cli, pull requests merged in 2022-01, with the labels that each got.

#5593 Allow dealerdirect/phpcodesniffer-composer-installer
  composer.json
Labels: scope:distribution

#5556 Update credits
  bin/wp
Labels: scope:documentation

#5551 Add missing docblocks
  php/WP_CLI/Completions.php
  php/WP_CLI/PackageManagerEventSubscriber.php
  php/WP_CLI/UpgraderSkin.php
Labels: scope:documentation

#5597 Detect and ignore BOMs
  features/bootstrap.feature
  features/config.feature
  php/WP_CLI/Runner.php
Labels: scope:framework, bug

#5599 Fix Composer stack tests
  composer.json
  features/bootstrap.feature
Labels: scope:testing

#5600 Use proper `WP_User_Query` for fetching users
  features/help.feature
  php/WP_CLI/Fetchers/User.php
Labels: scope:framework

#5605 Adapt VERSION from 2.5.1-alpha to 2.6.0-alpha
  VERSION
Labels: scope:distribution

#5604 Force the use of Mustache 2.14.1 security fix
  composer.json
Labels: scope:distribution
