Repository wp-cli/wp-cli, pull requests merged in 2022-10, with the labels that each got.

#5681 Add cache dir path to info output FIX #5580
  php/class-wp-cli.php
  php/commands/src/CLI_Command.php
  php/utils.php
Labels: command:cli, command:cli-info

#5684 Internalize `global_terms_enabled()`
  features/utils-wp.feature
  php/utils-wp.php
Labels: scope:testing

#5637 Add support for `docker-compose run` to the `ssh` option
  php/WP_CLI/Runner.php
  php/config-spec.php
  php/utils.php
  tests/test-utils.php
Labels: scope:framework

#5687 Move `WP_CLI_CONFIG_SPEC_FILTER_CALLBACK` test to `flags.feature`
  features/config.feature
  features/flags.feature
Labels: scope:testing

#5689 Fix proc_open_compat util on Windows
  php/utils.php
Labels: scope:framework, bug
