Repository wp-cli/wp-cli, pull requests merged in 2023-06, with the labels that each got.

#5797 Define `WP_CLI_ROOT` if needed
  php/WP_CLI/RequestsLibrary.php
Labels: bug

#5801 Fix link in README.md
  README.md
Labels: scope:documentation

#5802 Mention updating the homepage in the release process
  .github/ISSUE_TEMPLATE/4-REGULAR_RELEASE_CHECKLIST.md
  .github/ISSUE_TEMPLATE/5-PATCH_RELEASE_CHECKLIST.md
Labels: scope:meta
