Repository wp-cli/wp-cli, pull requests merged in 2023-02, with the labels that each got.

#5740 Add `composer phpcbf`
  composer.json
Labels: scope:testing

#5743 fix PHP Deprecation for 8.1
  php/WP_CLI/Iterators/Transform.php
Labels: scope:framework, bug

#5738 Use `WP_CLI_FORCE_USER_LOGIN=1` to force `--user=<login>`
  features/flags.feature
  php/WP_CLI/Fetchers/User.php
Labels: scope:framework
