Repository wp-cli/wp-cli, pull requests merged in 2023-01, with the labels that each got.

#5715 Fix return type of make_progress_bar
  php/utils.php
Labels: scope:documentation

#5711 Check that `proc_open()` is available in `Process::run()`
  php/WP_CLI/Process.php
Labels: scope:framework, bug

#5728 Use AWK instead of sed to create BOM in feature test
  features/config.feature
Labels: scope:testing

#5729 Improve docs for SHELL_PIPE
  php/utils.php
Labels: scope:documentation

#5722 Add runtime_args to options array for runcommand
  features/runcommand.feature
  php/class-wp-cli.php
Labels: internal-api:wp-cli-runcommand
