Repository wp-cli/wp-cli, pull requests merged in 2023-11, with the labels that each got.

#5853 Updated Inline PHP Documentation
  php/wp-settings-cli.php
Labels: scope:documentation

#5851 Remove `contrib-list.php`
  phpcs.xml.dist
  utils/contrib-list.php
Labels: scope:meta

#5849 Update tests to accommodate for SQLite
  features/bootstrap.feature
  features/framework.feature
  features/help.feature
  features/hook.feature
  features/requests.feature
  features/utils-wp.feature
  features/utils.feature
  php/utils-wp.php
Labels: scope:testing

#5861 Add missing documentation for `$data` attribute in `http_request()`
  php/utils.php
Labels: scope:documentation

#5863 Add `docker compose` command support in SSH command generation
  php/WP_CLI/Runner.php
Labels: scope:framework

#5850 Update release checklist template
  .github/ISSUE_TEMPLATE/4-REGULAR_RELEASE_CHECKLIST.md
Labels: scope:documentation

#5864 Move `RecursiveDataStructureTraverser` to `wp-cli/wp-cli` package
  php/WP_CLI/Exceptions/NonExistentKeyException.php
  php/WP_CLI/Traversers/RecursiveDataStructureTraverser.php
  tests/WP_CLI/Traversers/RecursiveDataStructureTraverserTest.php
Labels: scope:framework

#5866 Revert "Move `RecursiveDataStructureTraverser` to `wp-cli/wp-cli` package"
  php/WP_CLI/Exceptions/NonExistentKeyException.php
  php/WP_CLI/Traversers/RecursiveDataStructureTraverser.php
  tests/WP_CLI/Traversers/RecursiveDataStructureTraverserTest.php
Labels: scope:framework

#5865 Add missing required arguments when using `--prompt`
  features/prompt.feature
  php/WP_CLI/Dispatcher/Subcommand.php
Labels: scope:framework

#5868 Remove the pre-commit hook installation and its corresponding command
  composer.json
  utils/git-pre-commit-script
  utils/git-setup-pre-commit-hook
Labels: scope:testing

#5869 Add verbosity level and quiet flag in ssh command based on debug flag
  features/aliases.feature
  features/flags.feature
  php/WP_CLI/Runner.php
Labels: scope:framework

#5871 Revert the revert of the Move of `RecursiveDataStructureTraverser` to `wp-cli/wp-cli`
  php/WP_CLI/Exception/NonExistentKeyException.php
  php/WP_CLI/Traverser/RecursiveDataStructureTraverser.php
  tests/WP_CLI/Traversers/RecursiveDataStructureTraverserTest.php
Labels: scope:framework

#5872 Add `WP_CLI\Utils\has_stdin()` function
  php/utils.php
Labels: scope:framework

#5877 Updated Doc Block for Admin.php
  php/WP_CLI/Context/Admin.php
Labels: scope:documentation

#5879 Suggest 'network meta' intead of 'network option'
  features/runner.feature
  php/WP_CLI/Runner.php
Labels: scope:framework
