Repository wp-cli/wp-cli, pull requests merged in 2023-04, with the labels that each got.

#5759 Use -R instead of -r for fallback pager command
  php/commands/src/Help_Command.php
Labels: scope:framework

#5763 Update test to reflect warning when `--url=<url>` is provided
  features/bootstrap.feature
Labels: scope:testing

#5730 Make sure subcommand @alias definition respects @when definition
  features/command.feature
  php/WP_CLI/Dispatcher/Subcommand.php
  php/WP_CLI/Runner.php
Labels: scope:framework, bug

#5766 Added "wp cli alias is-group" subcommand.
  features/aliases.feature
  php/commands/src/CLI_Alias_Command.php
Labels: scope:framework
