Repository wp-cli/wp-cli, pull requests merged in 2023-05, with the labels that each got.

#5774 Upgrade WP-CLI to Requests v2
  composer.json
  features/requests.feature
  php/WP_CLI/Bootstrap/IncludeFrameworkAutoloader.php
  php/utils.php
  tests/mock-requests-transport.php
  tests/test-utils.php
Labels: scope:distribution, internal-api:wp-cli-utils-http-request

#5775 Use rtrim on phar-safe path to avoid double slash
  php/utils.php
Labels: bug

#5777 Extract cacert from Phar for cURL
  php/utils.php
Labels: scope:distribution, bug

#5780 Revert "Extract cacert from Phar for cURL"
  php/utils.php
Labels: scope:framework

#5778 Use `wp_cache_flush_runtime` if supported.
  php/utils-wp.php
Labels: command:cache-flush

#5781 Add bootstrap step to extract default CA certificate
  php/WP_CLI/Bootstrap/ExtractDefaultCaCertificate.php
  php/bootstrap.php
Labels: scope:distribution, bug

#5785 Add `RequestsLibrary::get_bundled_certificate_path()` method
  php/WP_CLI/RequestsLibrary.php
  php/utils.php
Labels: scope:bootstrap, internal-api:wp-cli-utils-http-request

#5786 Fallback to hardcoded folder when WPINC not defined
  php/WP_CLI/RequestsLibrary.php
Labels: bug

#5790 Ignore Requests deprecations in error handling for now
  php/WP_CLI/Process.php
Labels: scope:framework

#5791 Harden loading of upgrader
  php/utils-wp.php
Labels: bug
