Repository wp-cli/wp-cli, pull requests merged in 2023-08, with the labels that each got.

#5818 Escape shell command in `wp-cli update`
  php/commands/src/CLI_Command.php
Labels: command:cli-update

#5822 Revert "Escape shell command in `wp-cli update`"
  php/commands/src/CLI_Command.php
Labels: command:cli-update

#5823 Run test only on PHP 7.0+
  features/help.feature
Labels: scope:testing

#5825 Require PHP 7.0 for tests installing WP via Composer
  features/bootstrap.feature
Labels: scope:testing

#5817 Display a custom error message when `themes/functions.php` fatals
  features/skip-themes.feature
  php/utils-wp.php
Labels: scope:framework

#5828 Update type hint of $callable parameter in add_command() method
  php/class-wp-cli.php
Labels: scope:framework

#5805 Add support for the proxyjump key
  features/aliases.feature
  php/WP_CLI/Configurator.php
  php/WP_CLI/Runner.php
Labels: scope:framework

#5834 Update to WPCS v3
  composer.json
  php/WP_CLI/Completions.php
  php/WP_CLI/ComposerIO.php
  php/WP_CLI/Configurator.php
  php/WP_CLI/Dispatcher/CommandFactory.php
  php/WP_CLI/Dispatcher/CommandNamespace.php
  php/WP_CLI/Dispatcher/CompositeCommand.php
  php/WP_CLI/Dispatcher/Subcommand.php
  php/WP_CLI/DocParser.php
  php/WP_CLI/Extractor.php
  php/WP_CLI/Fetchers/Base.php
  php/WP_CLI/Fetchers/Comment.php
  php/WP_CLI/Fetchers/Post.php
  php/WP_CLI/Fetchers/User.php
  php/WP_CLI/FileCache.php
  php/WP_CLI/Formatter.php
  php/WP_CLI/Inflector.php
  php/WP_CLI/Iterators/CSV.php
  php/WP_CLI/Iterators/Exception.php
  php/WP_CLI/Iterators/Query.php
  php/WP_CLI/Iterators/Table.php
  php/WP_CLI/Loggers/Base.php
  php/WP_CLI/Loggers/Regular.php
  php/WP_CLI/NoOp.php
  php/WP_CLI/PackageManagerEventSubscriber.php
  php/WP_CLI/Process.php
  php/WP_CLI/Runner.php
  php/WP_CLI/SynopsisValidator.php
  php/WP_CLI/UpgraderSkin.php
  php/WP_CLI/WpHttpCacheManager.php
  php/WP_CLI/WpOrgApi.php
  php/boot-fs.php
  php/class-wp-cli-command.php
  php/class-wp-cli.php
  php/commands/src/CLI_Alias_Command.php
  php/commands/src/Help_Command.php
  php/dispatcher.php
  php/fallback-functions.php
  php/utils-wp.php
  php/utils.php
  php/wp-settings-cli.php
  phpcs.xml.dist
  tests/test-arg-validation.php
  tests/test-configurator.php
  utils/contrib-list.php
Labels: scope:testing
