Repository wp-cli/wp-cli, pull requests merged in 2024-04, with the labels that each got.

#5924 Ensure the alias has the leading `@` symbol when added
  features/aliases.feature
  php/class-wp-cli.php
  php/commands/src/CLI_Alias_Command.php
Labels: bug, command:cli-alias

#5929 Minor docblock improvements
  php/WP_CLI/Bootstrap/AutoloaderStep.php
  php/WP_CLI/Bootstrap/IncludeFallbackAutoloader.php
  php/WP_CLI/Dispatcher/Subcommand.php
Labels: scope:documentation

#5926 Add Signup fetcher
  php/WP_CLI/Fetchers/Signup.php
Labels: scope:framework

#5938 Fix broken Gutenberg test
  features/skip-themes.feature
Labels: scope:testing

#5936 Update docker runner to resolve docker path using `/usr/bin/env`
  php/WP_CLI/Runner.php
Labels: scope:framework

#5940 Revert "Add support for formatting boolean values in `WP_CLI\Formatter`"
  features/formatter.feature
  php/WP_CLI/Formatter.php
Labels: scope:framework

#5930 Fix `inherit` path in nested directory
  features/config.feature
  php/WP_CLI/Configurator.php
Labels: scope:framework, bug

#5939 Fix breaking multi-line CSV values on reading
  php/WP_CLI/Iterators/CSV.php
  tests/WP_CLI/Iterators/CSVTest.php
Labels: bug, contributor-day

#5921 Include any non default hook information in CompositeCommand
  features/help.feature
  php/WP_CLI/Dispatcher/CompositeCommand.php
  php/commands/src/CLI_Command.php
  php/commands/src/Help_Command.php
  php/utils.php
Labels: scope:documentation, command:help, contributor-day
