Repository wp-cli/wp-cli, pull requests merged in 2024-02, with the labels that each got.

#5893 WpOrgApi: allow specifying fields request param
  php/WP_CLI/WpOrgApi.php
Labels: internal-api:wp-org-api

#5900 Bump version to 2.10.0
  README.md
  VERSION
Labels: scope:distribution

#5908 Update Docs CLI_Command.php
  php/commands/src/CLI_Command.php
Labels: scope:documentation
