Repository wp-cli/wp-cli, pull requests merged in 2025-03, with the labels that each got.

#6037 Check PHP version requirement in update check
  composer.json
  features/cli-check-update.feature
  manifest.json
  php/commands/src/CLI_Command.php
Labels: command:cli-check-update

#6057 docker scheme: working-directory and stdin passing (reroll of #5974)
  features/flags.feature
  php/WP_CLI/Runner.php
Labels: scope:framework

#6058 Fix undefined variable issue
  php/commands/src/CLI_Command.php
Labels: bug

#6060 Temporarily remove `roave/security-advisories`
  composer.json
Labels: scope:testing

#6059 Improve command suggestions for taxonomies and post types
  features/runner.feature
  php/WP_CLI/Runner.php
Labels: command:cli-completions

#6061 Update `wp-cli/php-cli-tools` dependency
  composer.json
Labels: scope:distribution

#6065 Support multiple files in `WP_CLI_EARLY_REQUIRE`
  php/wp-cli.php
Labels: scope:bootstrap

#6062 Properly create missing wp cli config file when needed.
  composer.json
  features/config.feature
  php/WP_CLI/Runner.php
Labels: bug, command:cli-alias
