Repository wp-cli/wp-cli, pull requests merged in 2025-05, with the labels that each got.

#6088 Make sure existing `esc_like()` takes precedence
  php/utils.php
  tests/UtilsTest.php
Labels: scope:framework

#5987 Check for root earlier
  features/bootstrap.feature
  php/WP_CLI/Bootstrap/CheckRoot.php
  php/WP_CLI/Bootstrap/ConfigureRunner.php
  php/WP_CLI/Runner.php
  php/bootstrap.php
Labels: scope:bootstrap, bug

#6089 Escape CSV output
  php/utils.php
  tests/UtilsTest.php
Labels: bug, internal-api:wp-cli-utils-format-items

#6090 Use forked mustache library
  composer.json
Labels: scope:framework

#6092 Release v2.12.0
  README.md
  VERSION
Labels: scope:distribution

#6093 Require PHP 7.2.24+
  README.md
  composer.json
  manifest.json
  php/WP_CLI/SynopsisParser.php
  php/boot-fs.php
  php/class-wp-cli.php
  php/commands/src/CLI_Command.php
  php/commands/src/Help_Command.php
  php/utils.php
  phpcs.xml.dist
  tests/UtilsTest.php
Labels: scope:distribution
