Repository wp-cli/wp-cli, pull requests merged in 2025-02, with the labels that each got.

#5998 Add configurable user agent to WP-CLI to detect in firewall logs
  php/wp-cli.php
Labels: scope:framework

#6049 Revert "docker scheme: working-directory and stdin passing"
  php/WP_CLI/Runner.php
Labels: scope:testing, bug

#6041 Allow collecting PHPUnit coverage
  .gitignore
  phpunit.xml.dist
Labels: scope:testing
